### ISSUE TITLE
機能のアイデア

### ISSUE THREAD

**Issue by yuyaki** [jyogi-web/koro-front#12]
始めは見下ろし型の2Dだが、途中から3Dの傾き方の様な感じになる

**Comment by Oumasa** [comment]
コインを一定数とると操作があべこべになる

**Comment by Oumasa** [comment]
通過すると初期位置にワープ

**Comment by Oumasa** [comment]
いっそのこと敵とコインのアイコンを同じにして金属探知機みたいにコインの近くに行くと音が大きくなるというので敵とコインを音で判断してゴール目指す。

**Comment by yuyaki** [comment]
コイン八割取ったらどこからともなくビーム射出

**Comment by yuyaki** [comment]
なんならコインも右往左往動く

**Comment by yuyaki** [comment]
コイン半分取ったら迷路逆転、ゴールが左上に
